### PR TITLE
Adds script to prune nightly packages

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review 

## Description of changes

Occasionally we remove outdated nightly packages, which is a tedious process. Let's add a helper script so we can pass in the number of historical nightlies we want to keep, and remove the rest. Usage:

```
$ ./tools/prune-nightlies 
Will remove all but the newest 10 nightlies for each package.
Removing 97 packages for ./securedrop-client ...
Removing 106 packages for ./securedrop-export ...
Removing 0 packages for ./securedrop-keyring, found 0/10 nightlies
Removing 106 packages for ./securedrop-log ...
Removing 106 packages for ./securedrop-proxy ...
Removing 0 packages for ./securedrop-workstation-config, found 0/10 nightlies
Removing 0 packages for ./securedrop-workstation-grsec, found 0/10 nightlies
Removing 106 packages for ./securedrop-workstation-svs-disp ...
Removing 0 packages for ./securedrop-workstation-viewer, found 0/10 nightlies
```

The script doesn't commit or push changes, that's still up to a human, but if we like it, not hard to teach a bot to do it, too. 

## Checklist
- [x] Run `./tools/prune-nightlies` locally and observe changes. 
- [x] Observe all nightly packages older than 10 days are absent
- [x] Confirm that all packages for which nightlies do not exist, e.g. `securedrop-keyring`, remain unchanged

If the script works well for you, consider dropping the final "Revert" commit, so that packages are actually pruned as part of this PR.

### CODE REVIEW

**Review by maeve-fpf — APPROVED** [review]
Looks good! minor comments:

- If you are itching to use pipefail, grep could be replaced by `find` options (it won't exit 1, it'll just not output anything).
- I don't think `pushd`/`popd` are needed in a script with nothing else in it, because the shell's cwd disappears along with its process

And TIL:
```
$ xxd <<<""
00000000: 0a
```
That's... weird. Good to know.

**Comment by conorsch** [comment]
To whichever SD maintainer merges this: please wait 15m and check the https://apt-test.freedom.press/ url to make sure the changes went out. Package _removals_ won't be visible, given our use of reprepro and its preference to serve only the newest version of any given package, but the new script will be visible in the webroot.

**Review by emkll — APPROVED** [review]
Thanks @conorsch this script works well for me locally, so I dropped the final revert commit. Did not find the script in the webroot, but maybe I am missing something,

**Comment by conorsch** [comment]
>  Did not find the script in the webroot, but maybe I am missing something

I meant after merge, it'll be visible in https://apt-test.freedom.press/ ! Unrelated to this PR, I recently rebuilt that server, so I intend to keep an eye on the CD pieces to confirm still working well.

**Pull request merged**
